### ISSUE TITLE
Add Border to Neon Glow Themes input

### ISSUE THREAD

**Issue by deadcoder0904** [HackerThemes/theme-machine#1]
First of all, awesome project. It will be useful for so many.

The `Go`, `Hate it!` & `Action` must have a right border. I guess u missed it.

<img width="393" alt="Neon Glow" src="https://user-images.githubusercontent.com/16436270/32315992-5bfd9246-bfd4-11e7-8e16-9a665b9ddae1.png">

**Comment by arechsteiner** [comment]
This seems to be a bug in Bootstrap 4. I've reported it here: https://github.com/twbs/bootstrap/issues/24689

Thank you for participating in my project!

**Comment by deadcoder0904** [comment]
Cool dude its awesome 🎉 
Especially this theme
