### ISSUE TITLE
Build on Mac produces a "Fatal undefined"

### ISSUE THREAD

**Issue by kyledinh** [HackerThemes/theme-machine#4]
In the readme.md, I followed the instructions to build and received a "Fatal undefined" error.

When I dove deeper in, the error was in `buildBootstrap` and found this error:
```
[15:45:35] Error in plugin 'gulp-scss-lint'
Message:
    You need to have Ruby and scss-lint gem installed
```

When I installed that Ruby gem, everythings works!!

`gem install scss-lint`

Maybe an update in the readme.md could help other developers. BTW, great repo. THANKS!

**Comment by arechsteiner** [comment]
Thanks, I missed this dependency.
